global:
  lowerBoundX: 400 # Lower bound on x-axis
  upperBoundX: 1100 # Upper bound on x-axis
  lowerBoundY: 0 # Lower bound on y-axis
  upperBoundY: 630 # Upper bound on y-axis
  limit: 380 # Distance from the bottom of frame to the limit line of balls
  buttonSize: [201, 201] # Size of "start" button
  modeSize: [201, 171] # Size of "mode" button
  quitSize: [61, 41] # Size of "quit" button
  fixedFrameSize: [840, 630] # Size of frame
timeLimit:
  level1: 60.0
  level2: 60.0
  level3: 60.0
numberOfItems:
  level1: 10
  level2: 10
  level3: 10
